// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package lib

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	big "math/big"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7bc77e8bDecodeFunction(in *jlexer.Lexer, out *mintedNFT) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Sender":
			out.Sender = string(in.String())
		case "TokenId":
			if in.IsNull() {
				in.Skip()
				out.TokenId = nil
			} else {
				if out.TokenId == nil {
					out.TokenId = new(big.Int)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.TokenId).UnmarshalJSON(data))
				}
			}
		case "TokenUri":
			out.TokenUri = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7bc77e8bEncodeFunction(out *jwriter.Writer, in mintedNFT) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Sender\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sender))
	}
	{
		const prefix string = ",\"TokenId\":"
		out.RawString(prefix)
		if in.TokenId == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.TokenId).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"TokenUri\":"
		out.RawString(prefix)
		out.String(string(in.TokenUri))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v mintedNFT) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7bc77e8bEncodeFunction(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v mintedNFT) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7bc77e8bEncodeFunction(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *mintedNFT) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7bc77e8bDecodeFunction(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *mintedNFT) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7bc77e8bDecodeFunction(l, v)
}
